### ISSUE TITLE
Script no longer compatible with Ubuntu 18.04 or above

### ISSUE THREAD

**Issue by Snuggle** [dainnilsson/scripts#6]
Hey!

This script no longer compatible with Ubuntu 18.04 or above, as the directory that gnupg uses is no longer in `~/.gnupg/S.gpg-agent.ssh` but instead `${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh`. This seems to usually be `/run/user/1000/gnupg/S.gpg-agent.ssh`. In addition, gnome-keyring messes up things on the ssh-agent side.

As this tutorial is now broken and outdated, could I please suggest that it is now replaced by this Gist made by @artizirk, which was updated 15 days ago instead of 4 years ago?

https://gist.github.com/artizirk/d09ce3570021b0f65469cb450bee5e29

**Comment by Snuggle** [comment]
Could I please also request that the above Gist article is added to https://developers.yubico.com/PGP/SSH_authentication/ under "Ubuntu"? This is the only complete guide which has helped me get my Yubikey fully working with GPG/SSH authentication.

**Comment by artizirk** [comment]
I didn't know that my random notes were that useful. I have created a pull request to add my gist to the yubico developers page.

**Comment by dainnilsson** [comment]
Hi. This is a mostly dead repo with random personal scripts I sometime use or have used in the past. It's not intended as a tutorial or source of documentation, so it makes no sense for me to replace the script with a guide. I'll see to it that it gets removed from the developers.yubico.com page as it probably should never have been linked to from there, thanks for pointing that out!
